spring:
  application:
    name: servicio-catalogo
  cloud:
    function:
      definition: productoCreadoConsumidor
    stream:
      bindings:
        productoCreado-out-0:
          destination: producto-creado
        productoCreadoConsumidor-in-0:
          destination: producto-creado
          group: servicio-catalogo
